language: node_js
node_js:
  - "8"
  - "10"
cache: yarn
script: yarn ci
deploy:
  provider: npm
  email: iwanttobealight@yandex.ru
  skip_cleanup: true
  api_key:
    secure: Fzz8zZ9T0s1tCLvd3m6TedTe0ZPBBQOlsG2Ww7hjj98tJHK6ddd4HNcUCC1gDFHMdn74iSYrCsFHDvvXmLk68zbUr0GkyOhq8/x83SfS+l9fH8bZlIds3GMdKWjOrJpBrPC4L1KgR9qEdUffqZwsst8wBwe9Qq8cotZNX8xa4FDP6viz68AFlN0Vbu4wnjhtJ5vVqF67gM6CkXTRHNfjTeSzBcyJOYKM6FFMUGoziEcGXYS+a0f7x2xY+ze89kUxJ5oTZMnSyEbz3P0YKytv/W50DJmaDXv31dxFA/mZt4MsainBrdbweyLqVO+FoA1l+JpuPL6PZocIPf/14y0vdXGU8aDJdSN9qRZDyPWuxhq0LsyK5Szyq3bT0iaNdjMp5syY+zXMJtXyF+Ud91ICunk1Fj0qe+bsjqW+xUWJIpITJBlu5b0I47UlXri97wZtZX9I6QmLoA9l3BivGwEdcxXLk6w74h+9zF2M17xjs8l30JTZuYTxFjerKF+TMDtHKRGHa4h/13l3dqxAhHRHLA8RDXB218wtheSL0sVCGR0cVUNnge9MVAwVegjvEFMtFXPpdccD+AINKu6Gqvs8fMORg0ko9b6r0+7qLFZWQjmswxdGmXlsizndSgR7McDwaCSqE6ojhNRuAyIrPqLKempWjG3bMo2Vc+a6rv/AI88=
  on:
    tags: true
    repo: breadhead/react-file-uploader
