language: node_js
node_js:
  - "8"
  - "10"
cache: yarn
script: yarn ci
deploy:
  provider: npm
  email: iwanttobealight@yandex.ru
  api_key:
    secure: gxb0Nu/UA4F9c7antPbjl/r7kvC+8kfKTGbVclelcjDQYar9hsS7T8FpZmBVUaVnT5XvpN48wp2JUZd0nvzt5+V+cjCgXRvrg8Ll4kiXb00SgPoNYH90/tXfvcKo1DzN0Of+nlgWIWwTF8t2dGntYNkKWs1TtQbb0tzPZOGfkjeLBnY1RWMfejaAWiC3yGoJ7deTeyTjvM4ie9J7I8gYKN/GVPfvV4NtRn/a0+tQK9Mj17MRx94u2F1qzZg6Ds3mcfnbQjPhEhDwWvLlhME58A47uDxwa9pQgXOg9fz6RV4jmDYEjNr3Qup2gzuVXrjQXmktPDMyxSqvVlNRuRgzshJeWgxCdjAiDqlUekrYiUbeaefitfCT+UE8N21AfXUHgodODDXQnhjG+qzdhZAnizsr7OF92Yv/fYGm4W6FGYqbKjPx6xQYYXgfV8uhUeRELhvvXy24p0YIA3LeX0zdSJWf9dTxSCYvWYZPFYrVBVnHlgMLcnPkzsLRRkmgrYwmTNZapKiyr4ertyYqzeq6dzh+T0H/FGpBfdIDolsYhnsk2+3kbfBVilNi2guLv3JbBmXXFQ1KdbIg969I2krDYwoX9Cjkpoa9SA7pQmGvdYc2TtCeGAWui5zM8Enx+ATYjXlesrGLsECGWEuOqvGn1G6O3Bb1ZzW6+HRuBfrkCsg=
  on:
    tags: true
    repo: breadhead/react-file-uploader
